// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv1eP5mXvViGjsvIJCJcWh2KX3vYWYJfM',
    appId: '1:715197041903:web:2934f51cd5acda79fcdf1a',
    messagingSenderId: '715197041903',
    projectId: 'hydrosee-projects',
    authDomain: 'hydrosee-projects.firebaseapp.com',
    storageBucket: 'hydrosee-projects.firebasestorage.app',
    measurementId: 'G-YG7Z3MYCD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7JIElrte8khxtHJEA_7D3bIjQwCf49i4',
    appId: '1:715197041903:android:43b23ebca26aab06fcdf1a',
    messagingSenderId: '715197041903',
    projectId: 'hydrosee-projects',
    storageBucket: 'hydrosee-projects.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADd3djDrZudqdtToj-0FnOSEjrpkpAX78',
    appId: '1:715197041903:ios:2d0fa0024959b2aafcdf1a',
    messagingSenderId: '715197041903',
    projectId: 'hydrosee-projects',
    storageBucket: 'hydrosee-projects.firebasestorage.app',
    iosClientId: '715197041903-ro20370civdcrsvkgat3j98vhm5nolje.apps.googleusercontent.com',
    iosBundleId: 'com.example.pakcoyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADd3djDrZudqdtToj-0FnOSEjrpkpAX78',
    appId: '1:715197041903:ios:2d0fa0024959b2aafcdf1a',
    messagingSenderId: '715197041903',
    projectId: 'hydrosee-projects',
    storageBucket: 'hydrosee-projects.firebasestorage.app',
    iosClientId: '715197041903-ro20370civdcrsvkgat3j98vhm5nolje.apps.googleusercontent.com',
    iosBundleId: 'com.example.pakcoyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv1eP5mXvViGjsvIJCJcWh2KX3vYWYJfM',
    appId: '1:715197041903:web:5f68c789164a9099fcdf1a',
    messagingSenderId: '715197041903',
    projectId: 'hydrosee-projects',
    authDomain: 'hydrosee-projects.firebaseapp.com',
    storageBucket: 'hydrosee-projects.firebasestorage.app',
    measurementId: 'G-8Q7LNWDFPL',
  );

}